"use client";

import { motion, AnimatePresence } from "framer-motion";
import { useHistorianStore } from "@/lib/store";

export default function EssayModal() {
  const { essay, isEssayLoading, setEssay, currentNode } = useHistorianStore();

  const isOpen = essay !== null || isEssayLoading;

  return (
    <AnimatePresence>
      {isOpen && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm"
          onClick={() => !isEssayLoading && setEssay(null)}
        >
          <motion.div
            initial={{ opacity: 0, scale: 0.9, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.9, y: 20 }}
            transition={{ type: "spring", stiffness: 300, damping: 30 }}
            className="bg-parchment max-w-2xl w-full max-h-[85vh] overflow-auto rounded-2xl shadow-2xl border-2 border-sepia/30 p-8"
            onClick={(e) => e.stopPropagation()}
          >
            {/* Header */}
            <div className="flex items-start justify-between mb-6">
              <div>
                <h2 className="font-display text-2xl font-bold text-ink">
                  {currentNode.title}
                </h2>
                <p className="text-sm text-sepia mt-1 font-serif">
                  {currentNode.timeRange.start} — {currentNode.timeRange.end} | {currentNode.geographicScope}
                </p>
              </div>
              <button
                onClick={() => setEssay(null)}
                className="text-ink/40 hover:text-ink text-2xl leading-none p-1 transition-colors"
              >
                &times;
              </button>
            </div>

            {/* Content */}
            {isEssayLoading ? (
              <div className="space-y-4 py-8">
                <div className="flex justify-center">
                  <motion.div
                    animate={{ rotate: 360 }}
                    transition={{ duration: 2, repeat: Infinity, ease: "linear" }}
                    className="text-4xl"
                  >
                    📜
                  </motion.div>
                </div>
                <p className="text-center text-sepia font-serif italic">
                  The historian is writing your essay...
                </p>
                <div className="space-y-2 px-4">
                  {[...Array(8)].map((_, i) => (
                    <motion.div
                      key={i}
                      initial={{ width: "0%" }}
                      animate={{ width: `${60 + Math.random() * 40}%` }}
                      transition={{ delay: i * 0.15, duration: 0.5 }}
                      className="h-3 bg-sepia/10 rounded"
                    />
                  ))}
                </div>
              </div>
            ) : (
              <div className="prose prose-stone max-w-none">
                <div className="font-serif text-ink/90 leading-relaxed text-[15px] whitespace-pre-line first-letter:text-5xl first-letter:font-display first-letter:text-sepia first-letter:float-left first-letter:mr-2 first-letter:mt-1">
                  {essay}
                </div>
              </div>
            )}

            {/* Footer */}
            {!isEssayLoading && (
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 0.3 }}
                className="mt-8 pt-4 border-t border-sepia/20 flex justify-between items-center"
              >
                <span className="text-xs text-sepia/60 font-serif italic">
                  Generated by Super Historian
                </span>
                <button
                  onClick={() => setEssay(null)}
                  className="px-6 py-2 bg-navy text-white font-serif rounded-lg hover:bg-navy/80 transition-colors text-sm"
                >
                  Close
                </button>
              </motion.div>
            )}
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
